//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.01.01 at 01:29:59 AM GMT 
//


package com.gestionecole.matiere_ms.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.gestionecole.matiere_ms.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.gestionecole.matiere_ms.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UpdateMatiereRequest }
     * 
     */
    public UpdateMatiereRequest createUpdateMatiereRequest() {
        return new UpdateMatiereRequest();
    }

    /**
     * Create an instance of {@link UpdateMatiereResponse }
     * 
     */
    public UpdateMatiereResponse createUpdateMatiereResponse() {
        return new UpdateMatiereResponse();
    }

    /**
     * Create an instance of {@link GetMatiereByIdRequest }
     * 
     */
    public GetMatiereByIdRequest createGetMatiereByIdRequest() {
        return new GetMatiereByIdRequest();
    }

    /**
     * Create an instance of {@link AddMatiereRequest }
     * 
     */
    public AddMatiereRequest createAddMatiereRequest() {
        return new AddMatiereRequest();
    }

    /**
     * Create an instance of {@link MatiereInfo }
     * 
     */
    public MatiereInfo createMatiereInfo() {
        return new MatiereInfo();
    }

    /**
     * Create an instance of {@link GetMatiereResponse }
     * 
     */
    public GetMatiereResponse createGetMatiereResponse() {
        return new GetMatiereResponse();
    }

    /**
     * Create an instance of {@link DeleteMatiereRequest }
     * 
     */
    public DeleteMatiereRequest createDeleteMatiereRequest() {
        return new DeleteMatiereRequest();
    }

    /**
     * Create an instance of {@link AddMatiereResponse }
     * 
     */
    public AddMatiereResponse createAddMatiereResponse() {
        return new AddMatiereResponse();
    }

    /**
     * Create an instance of {@link DeleteMatiereResponse }
     * 
     */
    public DeleteMatiereResponse createDeleteMatiereResponse() {
        return new DeleteMatiereResponse();
    }

    /**
     * Create an instance of {@link ServiceStatus }
     * 
     */
    public ServiceStatus createServiceStatus() {
        return new ServiceStatus();
    }

}
