//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.01.01 at 01:29:59 AM GMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://model.matiere_ms.gestionEcole.com", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.gestionecole.matiere_ms.model;
